apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapi.fullname" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    {{- include "webapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "webapi.selectorLabels" . | nindent 4 }}
